### ISSUE TITLE
Releases signature verification?

### ISSUE THREAD

**Issue by danielfn** [AdoptOpenJDK/openjdk8-upstream-binaries#5]
Hi! I want to verify the releases with their respective `.sign` files but I don't know where to find the corresponding public key. Can anyone tell me who is signing these releases, please? Thanks

**Comment by jerboaa** [comment]
@danielfn We, Red Hat's OpenJDK team, sign this with our GPG key we use for OpenJDK source and vanilla binary releases. See:
http://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-March/011446.html

Pay attention to this info:
```
PGP Key: rsa4096/0x92EF8D39DC13168F (hkp://keys.gnupg.net)
Fingerprint = CA5F 11C6 CE22 644D 42C6  AC44 92EF 8D39 DC13 168F
```

You can fetch the key for example from:
https://keyserver1.pgp.com searching for `openjdk@redhat.com`

Once you've got the key I also suggest to get Andrew Haley's GPG key since he's signed the OpenJDK key. You can get that one from https://keyserver.ubuntu.com searching for `aph@redhat.com` for example. He is the upstream lead of OpenJDK 8u (and 11u). He has signed the `openjdk@redhat.com` key above.

For me this looks like:
```
$ gpg --list-signatures openjdk@redhat.com
pub   rsa4096 2019-03-15 [CA]
      CA5F11C6CE22644D42C6AC4492EF8D39DC13168F
uid           [  full  ] OpenJDK Team - Red Hat, Inc. <openjdk@redhat.com>
sig 3        92EF8D39DC13168F 2019-03-15  OpenJDK Team - Red Hat, Inc. <openjdk@redhat.com>
sig          CFDA0F9B35964222 2019-03-20  Andrew John Hughes <gnu.andrew@redhat.com>
sig          A5CD6035332FA671 2019-03-20  Andrew Haley <aph@redhat.com>
sub   rsa4096 2019-03-15 [S] [expires: 2023-03-14]
sig          92EF8D39DC13168F 2019-03-15  OpenJDK Team - Red Hat, Inc. <openjdk@redhat.com>
```

Once you have that established you can verify the signature with something like this:

```
gpg -u 0x9FF32E37 -v --verify <file>.sign <file>
```

**Comment by jerboaa** [comment]
Closing this as it's been answered. Feel free to reopen if there are more questions.

**Comment by danielfn** [comment]
Thank you for your thorough explanation @jerboaa , I have successfully verified the release!

I just want to point out that the key from https://keyserver1.pgp.com it's only signed by:

```
pub   rsa4096 2019-03-15 [CA]
      CA5F11C6CE22644D42C6AC4492EF8D39DC13168F
uid           [ unknown] OpenJDK Team - Red Hat, Inc. <openjdk@redhat.com>
sig 3        92EF8D39DC13168F 2019-03-15  OpenJDK Team - Red Hat, Inc. <openjdk@redhat.com>
sig          9710B89BCA57AD7C 2020-03-16  PGP Global Directory Verification Key
sub   rsa4096 2019-03-15 [S] [expires: 2023-03-14]
sig          92EF8D39DC13168F 2019-03-15  OpenJDK Team - Red Hat, Inc. <openjdk@redhat.com>
```

On the other hand, fetching it from https://keyserver.ubuntu.com or [hkp://keys.gnupg.net](http://keys.gnupg.net) does have Andrew Haley's signature.

**Comment by jerboaa** [comment]
@danielfn OK. Thanks for the heads-up.
